CFIT/Controllers/ChiTietHoiDongThiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CFIT.DAO;
using CFIT.EF;

namespace CFIT.Controllers
{
    public class ChiTietHoiDongThiController : Controller
    {
        // GET: ChiTietHoiDongThi
        public ActionResult Index()
        {
            DBContex db = new DBContex();

            return View(db.TTCSDL_ChiTietHoiDongThi.ToList());
        }
        public ActionResult Create()
        {
            DBContex db = new DBContex();
            List<TTCSDL_NhiemVu> cate = db.TTCSDL_NhiemVu.ToList();
            SelectList NhiemVuList = new SelectList(cate, "IDNhiemVu", "TenNhiemVu");
            ViewBag.NhiemVuList = NhiemVuList;
            List<TTCSDL_GiaoVien> catea = db.TTCSDL_GiaoVien.ToList();
            SelectList GiaoVienList = new SelectList(catea, "IDGiaoVien", "HoTen");
            ViewBag.GiaoVienList = GiaoVienList;
            return View();
        }
        [HttpPost]
        public ActionResult Create(TTCSDL_ChiTietHoiDongThi tTCSDL_ChiTietHoiDongThi)
        {
            tTCSDL_ChiTietHoiDongThi.ID_Hoi_Dong_Thi = 1;
            DBContex db = new DBContex();
            db.TTCSDL_ChiTietHoiDongThi.Add(tTCSDL_ChiTietHoiDongThi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
           
            DBContex db = new DBContex();
            var model = db.TTCSDL_ChiTietHoiDongThi.SingleOrDefault(x => x.IDGiaoVien == id);
            return View(model);
        }
    }
}

CFIT/Controllers/DanhSachNopTienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CFIT.EF;
namespace CFIT.Controllers
{
    public class DanhSachNopTienController : Controller
    {
        DBContex db = new DBContex();
        // GET: DanhSachNopTien
        public ActionResult Index()
        {
           
            return View(db.TTCSDL_DSNopTien.ToList());
        }
    }
}

CFIT/Controllers/GiaThiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CFIT.EF;
namespace CFIT.Controllers
{
    public class GiaThiController : Controller
    {
        // GET: GiaThi
        DBContex db = new DBContex();
        public ActionResult Index()
        {
            DBContex db = new DBContex();
            return View(db.TTCSDL_GiaOnThi.ToList());
        }
        public ActionResult Create()
        {
            DBContex db = new DBContex();
            List<TTCSDL_TrinhDo> cate = db.TTCSDL_TrinhDo.ToList();
            SelectList TrinhDoList = new SelectList(cate, "TrinhDo", "LoaiTrinhDo");
            ViewBag.TrinhDoList = TrinhDoList;

            List<TTCSDL_NhuCau> catea = db.TTCSDL_NhuCau.ToList();
            SelectList NhuCauList = new SelectList(catea, "NhuCau", "LoaiNhuCau");
            ViewBag.NhuCauList = NhuCauList;

            List<TTCSDL_HocVien> cateab = db.TTCSDL_HocVien.ToList();
            SelectList HocVienList = new SelectList(cateab, "LaHocVien", "HocTaiHocVien");
            ViewBag.HocVienList = HocVienList;
            return View();
        }
    }
}

CFIT/Controllers/GiaoVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CFIT.DAO;
using CFIT.EF;

namespace CFIT.Controllers
{
    public class GiaoVienController : Controller
    {
        // GET: GiaoVien
        public ActionResult Index()
        {
            GiaoVienDAO giaovien = new GiaoVienDAO();

            return View(giaovien.getALL());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(TTCSDL_GiaoVien tTCSDL_GiaoVien)
        {
            if (ModelState.IsValid)
            {
                GiaoVienDAO giaoVien = new GiaoVienDAO();
                giaoVien.Insert(tTCSDL_GiaoVien);
            }
            else
            {
                ModelState.AddModelError("", " không thành công");

            }

            return View();
        }
        public ActionResult Edit(int id)
        {
            GiaoVienDAO giaoVien = new GiaoVienDAO();

            return View(giaoVien.getByid(id));
        }
        [HttpPost]
        public ActionResult Edit(TTCSDL_GiaoVien tTCSDL_GiaoVien)
        {
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            DBContex db = new DBContex();
            var TTCSDL_GiaoVien = db.TTCSDL_GiaoVien.Find(id);
            db.TTCSDL_GiaoVien.Remove(TTCSDL_GiaoVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

CFIT/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CFIT.EF;
using CFIT.DAO;

namespace CFIT.Controllers
{
    public class HomeAdminController : Controller
    {
        // GET: HomeAdmin
        public ActionResult Index()
        {
            GiaoVienDAO giaoVien = new GiaoVienDAO();

            return View(giaoVien.getALL());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(true)]
        public ActionResult Create(TTCSDL_GiaoVien tTCSDL_GiaoVien)
        {
            if(ModelState.IsValid)
            {
                GiaoVienDAO giaoVien = new GiaoVienDAO();
                giaoVien.Insert(tTCSDL_GiaoVien);
            }
            else
            {
                ModelState.AddModelError("", "Đăng nhập không thành công");

            }


            return  RedirectToAction("Index");
        }
        public ActionResult Edit()
        {
            return View();
        }


    }
}

CFIT/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CFIT.EF;
using CFIT.DAO;

namespace CFIT.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(TTCDL_ThiSinh tTCDL_ThiSinh)
        {
            ThiSinhDAO thiSinhDAO = new ThiSinhDAO();
            thiSinhDAO.Insert(tTCDL_ThiSinh);
            DBContex db = new DBContex();
            db.TTCSDL_NhiemVu.SqlQuery("exec ")
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CFIT/Controllers/ThiSinhController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CFIT.DAO;
using CFIT.EF;

namespace CFIT.Controllers
{
    public class ThiSinhController : Controller
    {
        // GET: ThiSinh
        public ActionResult Index()
        {
            DBContex dBContex = new DBContex();
            ThiSinhDAO thiSinhDAO = new ThiSinhDAO();
            return View(thiSinhDAO.getALL());
        }
    }
}

CFIT/Views/ChiTietHoiDongThi/Create.cshtml
@model CFIT.EF.TTCSDL_ChiTietHoiDongThi

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutsAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TTCSDL_ChiTietHoiDongThi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       

        <div class="form-group">
            @Html.LabelFor(model => model.IDGiaoVien, "IDGiaoVien", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDGiaoVien", (IEnumerable<SelectListItem>)ViewBag.GiaoVienList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDGiaoVien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDNhiemVu, "IDNhiemVu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDNhiemVu", (IEnumerable<SelectListItem>)ViewBag.NhiemVuList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDNhiemVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CFIT/Views/ChiTietHoiDongThi/Createaa.cshtml
@model CFIT.EF.TTCSDL_ChiTietHoiDongThi

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutsAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_Hoi_Dong_Thi, "ID_Hoi_Dong_Thi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.ID_Hoi_Dong_Thi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDGiaoVien, "IDGiaoVien", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDGiaoVien", (IEnumerable<SelectListItem>)ViewBag.GiaoVienList, htmlAttributes: new { @class = "form-control" })
                
                @Html.ValidationMessageFor(model => model.IDGiaoVien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDNhiemVu, "IDNhiemVu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDNhiemVu", (IEnumerable<SelectListItem>)ViewBag.NhiemVuList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDNhiemVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

    @Scripts.Render("~/bundles/jqueryval")

CFIT/Views/ChiTietHoiDongThi/Edit.cshtml
@model CFIT.EF.TTCSDL_ChiTietHoiDongThi

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutsAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TTCSDL_ChiTietHoiDongThi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Hoi_Dong_Thi)

        @Html.HiddenFor(model => model.IDGiaoVien)

        @Html.HiddenFor(model => model.IDNhiemVu)

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CFIT/Views/ChiTietHoiDongThi/Index.cshtml
@model IEnumerable<CFIT.EF.TTCSDL_ChiTietHoiDongThi>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutsAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TTCSDL_GiaoVien.HoTen)
        </th>
        <th>
            <label>Đơn Vị  </label>
        </th>
        <th>
            <label>Cấp Bậc</label>
        </th>

        <th>
            @Html.DisplayNameFor(model => model.TTCSDL_NhiemVu.TenNhiemVu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Note)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TTCSDL_GiaoVien.HoTen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TTCSDL_GiaoVien.DonVi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TTCSDL_GiaoVien.CapBac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TTCSDL_NhiemVu.TenNhiemVu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Note)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new {  id=item.IDGiaoVien }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

CFIT/Views/DanhSachNopTien/Index.cshtml
@model IEnumerable<CFIT.EF.TTCSDL_DSNopTien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutsAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <label> Họ Tên </label>
        </th>
        <th>
            <label>Ngày Sinh </label>
        </th>
        <th>
            <label>CMT </label>
        </th>
        <th>
            <label>Thuộc HV</label>
        </th>

        <th>
            <label>Ôn Thi </label>
        </th>
        <th>
            <label>Thi </label>
        </th>
        <th>
            <label>Tổng Tiền </label>
        </th>
        <th></th>
    </tr>


    @{
        decimal TOng;
        string x;
    }
    @foreach (var item in Model)
    {
        TOng = item.TTCSDL_GiaOnThi.GiaOnThi + item.TTCSDL_GiaOnThi.GiaThi;
        
            if (item.TTCDL_ThiSinh.LaHocVien)
            {
                x = "Có";
            }
            else
            {
                x = "Không";
            }
        
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TTCDL_ThiSinh.HoTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TTCDL_ThiSinh.NgaySinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TTCDL_ThiSinh.SoCMT)
            </td>
            <td>
                @x
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TTCSDL_GiaOnThi.GiaOnThi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TTCSDL_GiaOnThi.GiaThi)
            </td>
            <td>
                @TOng
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID_NopTien }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID_NopTien }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID_NopTien })
            </td>
        </tr>
    }

</table>

CFIT/Views/GiaThi/Create.cshtml
@model CFIT.EF.TTCSDL_GiaOnThi

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutsAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TTCSDL_GiaOnThi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_GiaOnThi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_GiaOnThi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_GiaOnThi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrinhDo, "TrinhDo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TrinhDo", (IEnumerable<SelectListItem>)ViewBag.TrinhDoList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrinhDo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LaHocVien, "LaHocVien", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LaHocVien", (IEnumerable<SelectListItem>)ViewBag.HocVienList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LaHocVien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaOnThi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaOnThi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaOnThi, "", new { @class = "text-danger" })
            </div>
           
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDKyThi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDKyThi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDKyThi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NhuCau, "NhuCau", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NhuCau", (IEnumerable<SelectListItem>)ViewBag.NhuCauList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NhuCau, "", new { @class = "text-danger" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaThi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaThi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaThi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaKyThi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaKyThi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaKyThi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CFIT/Views/GiaThi/Index.cshtml
@model IEnumerable<CFIT.EF.TTCSDL_GiaOnThi>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutsAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <label>Học Tại Học Viện</label>
        </th>
        <th>
            <label>Nhu Cầu</label>
        </th>
        <th>
            <label>Trình Độ </label>
        </th>
        <th>
            <label>Giá ôn thi</label>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IDKyThi)
        </th>
        <th>
            <label>Giá thi</label>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TTCSDL_HocVien.HocTaiHocVien)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TTCSDL_NhuCau.LoaiNhuCau)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TTCSDL_TrinhDo.LoaiTrinhDo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GiaOnThi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IDKyThi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GiaThi)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID_GiaOnThi }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID_GiaOnThi }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID_GiaOnThi })
        </td>
    </tr>
}

</table>

CFIT/Views/GiaoVien/Create.cshtml
@model CFIT.EF.TTCSDL_GiaoVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutsAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TTCSDL_GiaoVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonVi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonVi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonVi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CapBac, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="CapBac" aria-controls="dataTables-example" class="form-control input-sm">
                    <option value="Thiếu Úy">Thiếu Úy</option>
                    <option value="Trung Úy">Trung Úy</option>
                    <option value="Đại Úy">Đại Úy</option>
                    <option value="Thiếu Tá">Thiếu Úy</option>
                    <option value="Trung Tá">Thiếu Úy</option>
                    <option value="Đại Tá">Thiếu Úy</option>
                </select>
                @Html.ValidationMessageFor(model => model.CapBac, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


    @Scripts.Render("~/bundles/jqueryval")

CFIT/Views/Shared/401.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}
@section header{
    Lỗi không có quyền
    }
<div class="alert alert-danger">
    Bạn không có quyền truy cập.
</div>

CFIT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chứng Chỉ Công Nghệ Thông Tin</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></button>
                @Html.ActionLink("Chứng Chỉ Công Nghệ Thông Tin", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Đăng Nhập", "Index", "GiaoVien", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
            </ul>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>